#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# routes.yaml

# config/routes.yaml
region_map:
    path: /region_map
    controller: App\Controller\BackendController::regionMap